apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  jenkins-deploy
spec:
  replicas: 2
  minReadySeconds: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  jenkins
    spec:
      containers:
      - image:  jenkins
        name:  jenkins-pod     
        ports:
        - containerPort:  8080