apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello-pod
        image:  nginx
        ports:
        - containerPort: 80